
FIND_PATH(MONGOOSE_INCLUDE_DIR mongoose.h
  "$ENV{LIB_DIR}/include"
  "$ENV{LIB_DIR}/include/mongoose"
  "${CMAKE_SOURCE_DIR}/../third-party/mongoose"
  NO_DEFAULT_PATH
  )
file(GLOB_RECURSE MONGOOSE_SRC_FILES "${CMAKE_SOURCE_DIR}/../third-party/mongoose/*.c")

IF (MONGOOSE_INCLUDE_DIR AND MONGOOSE_SRC_FILES)
  SET(MONGOOSE_FOUND TRUE)
ENDIF (MONGOOSE_INCLUDE_DIR AND MONGOOSE_SRC_FILES)

MESSAGE(STATUS "Mongoose Include: ${MONGOOSE_INCLUDE_DIR}")

IF (MONGOOSE_FOUND)
MESSAGE(STATUS "Found Mongoose Embedded WebServer. ")
ELSE (MONGOOSE_FOUND)
MESSAGE(FATAL_ERROR "Mongoose is missing.")
ENDIF (MONGOOSE_FOUND)
