#!/bin/bash

DEFAULT_ARCHIVE="/tmp/conf.tar.gz"
ARCHIVE="${DEFAULT_ARCHIVE}"

DEFAULT_DATADIR="/var/tmp/ntopng"
DATADIR="${DEFAULT_DATADIR}"
DATADIR_SET=false

STAGING_DIR=""

SAVED_SUFFIX=".ntopngsaved"

ACTION=""

function print_usage() {
echo "Executing ntopng configuration backup/restore utility"
    echo "Usage:"
    echo "`basename $0` -a restore [-c archive.tar.gz] [-d datadir]"
    echo "`basename $0` -a backup  [-c archive.tar.gz] [-d datadir]"
    echo ""
    echo "Restore:"
    echo "`basename $0` -a restore [-c archive.tar.gz] [-d datadir]"
    echo "[-c archive.tar.gz]"
    echo "  The path to a compressed archive containing"
    echo "  a backup that has to be restored. The only compressed archives"
    echo "  accepted are those created from the web interface or with this script."
    echo "  When no path is specified, the default ${DEFAULT_ARCHIVE}"
    echo "  path is used."
    echo "[-d datadir]"
    echo "  The path to the ntopng data directory where the restore will place the files."
    echo "  When no path is specified, the path indicated in the compressed archive"
    echo "  is used."
    echo "  The data directory must exist on the system. Resored files will take the"
    echo "  ownership (user and group) of the existing directory."
    echo ""
    echo "Backup:"
    echo "`basename $0` -a backup  [-c archive.tar.gz] [-d datadir]"
    echo "[-c archive.tar.gz]"
    echo  " The path of the compressed archive that will be output."
    echo  " When no path is specified, the compressed archive will be output"
    echo  " to the default ${DEFAULT_ARCHIVE}."
    echo "[-d datadir]"
    echo "  The path to the ntopng data directory used to backup files."
    echo "  When no path is specified, the default ${DEFAULT_DATADIR} path is used."
    echo "pathname1"
    echo "  The path to a directory or file that should be backed up"
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -a|--action)
    ACTION="$2"
    shift
    shift
    ;;
    -c|--archive)
    ARCHIVE="$2"
    shift
    shift
    ;;
    -d|--data-dir)
    DATADIR="$2"
    DATADIR_SET=true
    shift
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

function cleanup() {
    if [ "$?" = "0" ]; then
	# exited with SUCCESS
	if [ $ACTION == "restore" ]; then
		rm -rf "${ARCHIVE}"
	fi
    else
	# exited with ERROR
	:
    fi

    rm -rf "${STAGING_DIR}"
}

trap cleanup EXIT

if [[ ( $ACTION != "backup" && $ACTION != "restore" ) ]]; then
    print_usage
    exit 1
fi

if [[ ( $ACTION == "restore" ) && ( ${#POSITIONAL[@]} -gt 0 ) ]]; then
    print_usage
    exit 1
fi

function setup_staging_dir() {
    # the temp directory used, within $DIR
    # omit the -p parameter to create a temporal directory in the default location
    STAGING_DIR=`mktemp -d`

    # check if tmp dir was created
    if [[ ! "$STAGING_DIR" || ! -d "$STAGING_DIR" ]]; then
	echo "Could not create temp directory"
	exit 1
    fi
}

function copy_to_staging_dir() {
    local PATHNAME="$1"
    local DST="$2"

    if [ ! -f "${PATHNAME}" ] && [ ! -d "${PATHNAME}" ]; then
	return
    fi

    if [[ "${PATHNAME}" != /* ]]; then
	echo "Skipping ${PATHNAME}. Only absolute paths allowed"
	return
    fi

    # recreate the tree into the staging directory
    local STAGED="${STAGING_DIR}/${DST}"
    mkdir -p "${STAGED}"

    # copy to the staging area
    if [ -f "${PATHNAME}" ]; then
	cp -p "${PATHNAME}" "${STAGED}"
    else
	cp -Rp "${PATHNAME}/." "${STAGED}"
    fi

    # echo "${STAGING_DIR}"
    # find ${STAGING_DIR}
}

function manifest_to_staging_dir() {
    local DST="${STAGING_DIR}/MANIFEST"

    # write a timestamp and the original data directory to a manifest file
    echo "Time: $(date)" >> "${DST}"
    echo "__datadir: ""${DATADIR}" >> "${DST}"
}

function backup_to_staging_dir() {
    copy_to_staging_dir "/etc/ntopng" "__etc_ntopng"
    copy_to_staging_dir "/etc/ntopng.license" "__license"
    copy_to_staging_dir "/etc/nedge.license" "__license"
    copy_to_staging_dir "${DATADIR}/runtimeprefs.json" "__datadir"
    copy_to_staging_dir "${DATADIR}/system.config" "__datadir"
    manifest_to_staging_dir
}

function sanitize_staging_dir() {
    # Throw away any possible executable file from the staging area
    # executables include binaries but also shell scripts
    find "${STAGING_DIR}" -executable -type f  -exec rm -rf {} \;

    # Throw away backup files
    find "${STAGING_DIR}" -type f -name "*~" -exec rm -rf {} \;

    # Throw away previously backed up ntopng files
    find "${STAGING_DIR}" -type f -name "*${SAVED_SUFFIX}" -exec rm -rf {} \;

    # Throw away empty files
    find "${STAGING_DIR}" -type f -size 0 -exec rm -rf {} \;

    # Throw away everything else BUT pure ASCII files
    find "${STAGING_DIR}" -type f -name '*.*' -print0 |
    while IFS= read -r -d '' FL; do
	if ! `file "${FL}" | grep -qc "ASCII text";`; then
	    rm -rf "${FL}"
	    echo "Non-ASCII file ""${FL}"" ignored"
	fi
    done

    # echo "${STAGING_DIR}"
    # find ${STAGING_DIR}
}

function staging_dir_to_archive() {
    # remove the archive if it exists
    rm -rf "${ARCHIVE}"
    # compress the staging dir to a compressed archive
    # by discaring the current path to the staging dir
    tar cfz "${ARCHIVE}" -C "${STAGING_DIR}" .
}

function check_tar_file() {
    # make sure it's a tar archive
    if ! `file "${ARCHIVE}" | grep -qc "gzip compressed data";`; then
	echo "Unrecognized file format for ${ARCHIVE}: expecting gzip compressed data"
	exit 1
    fi
}

function check_tar_contents() {
    # must contain __etc_ntopng
    if ! `tar tf "${ARCHIVE}" ./__etc_ntopng/ >/dev/null 2>&1`; then
	echo "Compressed archive $1 does not contain __etc_ntopng"
	exit 1
    fi

    # must contain __datadir
    if ! `tar tf "${ARCHIVE}" ./__datadir/ >/dev/null 2>&1`; then
	echo "Compressed archive $1 does not contain __datadir"
	exit 1
    fi

    # must contain a manifest file
    if ! `tar tf "${ARCHIVE}" ./MANIFEST >/dev/null 2>&1`; then
	echo "Compressed archive $1 does not contain MANIFEST"
	exit 1
    fi
}

function parse_manifest() {
    local ARCHIVE_DATADIR=`cat "${STAGING_DIR}"/MANIFEST | grep "__datadir:" |  awk -F ": " '{print $2}'`

    if [ "${DATADIR_SET}" = false ] && [ ! -z "${ARCHIVE_DATADIR}" ]; then
	DATADIR="${ARCHIVE_DATADIR}"
	echo "Restoring to MANIFEST data directory ${DATADIR}"
    elif [ "${DATADIR_SET}" = true ]; then
	echo "Restoring to command line data directory ${DATADIR}"
    else
	echo "Restoring to defaul data directory ${DATADIR}"
    fi
}

function tar_file_to_staging_dir() {
    echo "Extracting compressed archive contents to ${STAGING_DIR}"
    tar xfz "${ARCHIVE}" -C "${STAGING_DIR}" || exit 1
}

function check_current_system_dirs() {
    if [ ! -d "/etc/ntopng" ]; then
	echo "Directory /etc/ntopng is missing from the system, unable to restore."
	exit 1
    fi

    # DATADIR is empty when system.config and runtimeprefs.json are not
    # going to be restored
    if [ ! -z "${DATADIR}" ] && [ ! -d "${DATADIR}" ]; then
	echo "Directory ${DATADIR} missing from the system, unable to restore."
	exit 1
    fi
}

function restore_and_save_file() {
    local SRC="$1"  # full path to the source file
    local DST_DIR="$2" # destination directory
    local OWNERSHIP="$3" # ownership to execute chown

    if [ ! -z "${SRC}" ] && [ -f "${SRC}" ] && [ ! -z "${DST_DIR}" ] && [ -d "${DST_DIR}" ]; then
	local SRC_BASENAME=`basename "${SRC}"`
	local DST="${DST_DIR}/${SRC_BASENAME}"

	if [ -f "${DST}" ]; then
	    # make a backup copy of the file before overwriting it
	    local SAV="${DST}${SAVED_SUFFIX}"

	    rm -rf "${SAV}" || exit 1
	    echo "Old file ""${SAV}"" removed"
	    cp -Rp "${DST}" "${SAV}" || exit 1
	    echo "File ""${DST}"" saved to ""${SAV}"
	fi

	# put the recovered file in place
	cp -Rp "${SRC}" "${DST}" || exit 1
	echo "File ""${DST}"" restored"

	# possibly change the ownership
	if [ ! -z "${OWNERSHIP}" ]; then
	    chown "${OWNERSHIP}" "${DST}" || exit 1
	    echo "File ""${DST}"" permissions set to ""${OWNERSHIP}"
	fi
    fi
}

function restore_files() {
    # restore /etc/ntopng files
    find "${STAGING_DIR}/__etc_ntopng"  -maxdepth 1 -type f -name '*.*' -print0 |
    while IFS= read -r -d '' FL; do
	restore_and_save_file "${FL}" "/etc/ntopng"
    done

    if [ -f "${STAGING_DIR}/__license/ntopng.license" ]; then
	restore_and_save_file "${STAGING_DIR}/__license/ntopng.license" "/etc" "root:root"
    fi

    if [ -f "${STAGING_DIR}/__license/nedge.license" ]; then
	restore_and_save_file "${STAGING_DIR}/__license/nedge.license" "/etc" "root:root"
    fi

    if [ -z "${DATADIR}" ] || [ ! -d "${DATADIR}" ]; then
	# nothing to do, the either not existing or not a directory
	return
    fi

    # Get the ownership of the data directory
    # extracted files will be chowned to make sure they have the same
    # owner and group of the data directory
    local USER_GROUP=`ls -ld ${DATADIR} | awk '{print $3":"$4}'`
    # will be something like root:root nobody:nogroup

    if [ -z "${USER_GROUP}" ]; then
	echo "Unable to retrieve user and group of ${DATADIR}"
	exit 1
    fi

    if [ -f "${STAGING_DIR}/__datadir/system.config" ]; then
	restore_and_save_file "${STAGING_DIR}/__datadir/system.config" "${DATADIR}" "${USER_GROUP}"
    fi

    if [ -f "${STAGING_DIR}/__datadir/runtimeprefs.json" ]; then
	restore_and_save_file "${STAGING_DIR}/__datadir/runtimeprefs.json" "${DATADIR}" "${USER_GROUP}"
    fi
}

if [ $ACTION == "backup" ]; then
    echo "Backing up..."

    setup_staging_dir
    backup_to_staging_dir
    sanitize_staging_dir
    staging_dir_to_archive

elif [ $ACTION == "restore" ]; then
    echo "Restoring..."

    # preliminary checks
    check_tar_file
    check_tar_contents

    # actual restore
    setup_staging_dir
    tar_file_to_staging_dir
    parse_manifest
    check_current_system_dirs
    sanitize_staging_dir
    restore_files
else
    # never reached
    echo "Unknown action $ACTION"
    exit 1
fi

exit 0
