           {
           title: "Client",
         field: "column_client",
         sortable: true,
         },
           {
           title: "Server",
         field: "column_server",
         sortable: true,
         },
           {
           title: "Duration",
         field: "column_duration",
         sortable: true,
                 css: { 
              textAlign: 'center'
             }
             },
