<p>&nbsp;<p><small><b>NOTE</b></small>
<ol>
<li> <small><i class="icon-map-marker"></i> <span id=mylocation></span></small>
<li> <small>In order to visualize maps you must:</small>
<ol>
<li> <small>Have a working Internet connection.</small>
<li> <small>Have compiled ntopng with geolocation and started with it.</small>
<li> <small>Have active flows between peers with public IP addresses.</small>
</ol>
<li> <small>HTML <A HREF=http://diveintohtml5.info/geolocation.html>browser geolocation</A> is used to place on map hosts based on unknown locations.</small>
</ul>
</small>
