<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to @NTOP_PRODUCT_NAME@</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="@HTTP_PREFIX@/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/bootstrap/css/bootstrap-theme.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="@HTTP_PREFIX@/css/rickshaw.css">
    <link type="text/css" rel="stylesheet" href="@HTTP_PREFIX@/css/jquery-ui.css">
    <link href="@HTTP_PREFIX@/css/dc.css" rel="stylesheet">

<style>
.flag {
	width: 16px;
	height: 11px;
	margin-top: -5px; /* Luca */
	background:url(@HTTP_PREFIX@/img/flags.png) no-repeat
}
</style>


    <link href="@HTTP_PREFIX@/css/flags.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/pie-chart.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/rickshaw.css" rel="stylesheet">
    <!-- http://kamisama.github.io/cal-heatmap/v2/ -->
    <link href="@HTTP_PREFIX@/css/cal-heatmap.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/nv.d3.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/bootstrap-duallistbox.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/bootstrap-slider.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/css/bootstrap-nav-wizard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="@HTTP_PREFIX@/js/html5shiv.js"></script>
    <![endif]-->

    <link href="@HTTP_PREFIX@/css/ntopng.css?@NTOP_STARTUP_EPOCH@" rel="stylesheet">
    <link rel="stylesheet" href="@HTTP_PREFIX@/css/bootstrap-datetimepicker.css" />

    <link href="@HTTP_PREFIX@/css/custom_theme.css?@NTOP_STARTUP_EPOCH@" rel="stylesheet">
    <script type="text/javascript" src="@HTTP_PREFIX@/js/jquery_bootstrap.min.js?@NTOP_STARTUP_EPOCH@"></script>
    <script type="text/javascript" src="@HTTP_PREFIX@/js/deps.min.js?@NTOP_STARTUP_EPOCH@"></script>
    <script type="text/javascript" src="@HTTP_PREFIX@/js/ntop.min.js?@NTOP_STARTUP_EPOCH@"></script>
  </head>
<body>

  <div class="container-narrow">


