<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to @NTOP_PRODUCT_NAME@</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="@HTTP_PREFIX@/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/bootstrap/css/bootstrap-theme.css" rel="stylesheet">
    <link href="@HTTP_PREFIX@/font-awesome/css/font-awesome.css" rel="stylesheet">
    <script src="@HTTP_PREFIX@/js/jquery.js"></script>
    <script src="@HTTP_PREFIX@/js/jquery-ui.js"></script>
    <script src="@HTTP_PREFIX@/js/bootstrap.js"></script>
    <link type="text/css" rel="stylesheet" href="@HTTP_PREFIX@/css/jquery-ui.css">
    <link type="text/css" rel="stylesheet" href="@HTTP_PREFIX@/css/rickshaw.css">
    <script src="@HTTP_PREFIX@/js/validator.js"></script>
<style>
.flag {
	width: 16px;
	height: 11px;
	margin-top: -5px; /* Luca */
	background:url(@HTTP_PREFIX@/img/flags.png) no-repeat
}
</style>

    <link href="@HTTP_PREFIX@/css/ntopng.css" rel="stylesheet">
  </head>
<body>

  <div class="container-narrow">


