			     {
			     title: "Hosts",
				 field: "column_hosts",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
			     {
			     title: "ARP Sent",
				 field: "column_arp_sent",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
				   {
			     title: "ARP Received",
				 field: "column_arp_rcvd",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
			     {
			     title: "Seen Since",
				 field: "column_since",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
