			     {
			     title: "Hosts",
				 field: "column_hosts",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
			     {
			     title: "Alerts",
				 field: "column_alerts",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }				 
				 },
			     {
			     title: "Seen Since",
				 field: "column_since",
				 sortable: true,
                             css: {
			        textAlign: 'center'
			     }

				 },
