{
 "title": "Host Details",
 "description": "A Dashboard used to integrate ntopng data with Grafana, using the support of ClickHouse to store Historical Flows and InfluxDB to store timeseries",
 "tags": [
  "host",
  "network analysis",
  "flows",
  "traffic",
  "ntopng"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host " }
  ]
 },
 "panels": [
  {
   "title": "Host Flows",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT IPv4NumToString(IPV4_SRC_ADDR) Client_IPv4, IPv4NumToString(IPV4_DST_ADDR) Server_IPv4, IPv6NumToString(IPV6_SRC_ADDR) Client_IPv6, IPv6NumToString(IPV6_DST_ADDR) Server_IPv6, SRC_LABEL as Cli_Hostname, DST_LABEL as Srv_Hostname, IP_SRC_PORT as Cli_Port, IP_DST_PORT as Srv_Port, VLAN_ID as Vlan, PROTOCOL as L4_Proto, L7_PROTO as App_Proto, L7_PROTO_MASTER as nDPI_Proto, L7_CATEGORY as Category, INFO as Info, SCORE as Score, PACKETS as Packets, TOTAL_BYTES as Bytes, FIRST_SEEN as First_Seen, LAST_SEEN as Last_seen, COMMUNITY_ID as Community_ID, ABS(Last_seen - First_Seen) as TIME_DELTA, (Bytes / (TIME_DELTA + 1)) * 8 as Throughput FROM ntopng.flows WHERE ( FIRST_SEEN >= $__fromTime ) AND ( LAST_SEEN <= $__toTime ) AND ( IPV4_SRC_ADDR = IPv4StringToNum('${host}') OR IPV4_DST_ADDR = IPv4StringToNum('${host}') OR IPV6_SRC_ADDR = IPv6StringToNum('${host}') OR IPV6_DST_ADDR = IPv6StringToNum('${host}') ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Host Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10m) FROM \"host:traffic\" WHERE (\"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 10m) FROM \"host:traffic\" WHERE (\"host\" =  '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Score",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:score",
     "query": "SELECT mean(\"score_as_cli\") + mean(\"score_as_srv\") FROM \"host:score\" WHERE (\"host\" = '${host}') AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "score_as_cli" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "score_as_srv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Protocol Traffic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "Amazon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" = '${host}' AND \"protocol\" = 'Amazon') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "Amazon" }
     ]
    },
    {
     "alias": "ICMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" = '${host}' AND \"protocol\" = 'ICMP') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "Amazon" }
     ]
    },
    {
     "alias": "DNS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" =  '${host}'  AND \"protocol\" = 'DNS') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "DNS" }
     ]
    },
    {
     "alias": "Youtube",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" =  '${host}'  AND \"protocol\" = 'YouTube') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "YouTube" }
     ]
    },
    {
     "alias": "HTTP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" =  '${host}'  AND \"protocol\" = 'HTTP') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "HTTP" }
     ]
    },
    {
     "alias": "Discord",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi\" WHERE (\"host\" =  '${host}'  AND \"protocol\" = 'Discord') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "HTTP" }
     ]
    }
   ]
  },
  {
   "title": "Category Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "Advertisement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m), non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Advertisement' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Advertisement" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Chat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Chat' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Chat" }
     ]
    },
    {
     "alias": "Cloud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Cloud' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Cloud" }
     ]
    },
    {
     "alias": "Collaborative",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Collaborative' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Collaborative" }
     ]
    },
    {
     "alias": "ConnCheck",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'ConnCheck' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "ConnCheck" }
     ]
    },
    {
     "alias": "Database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Database' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Database" }
     ]
    },
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Download' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Download" }
     ]
    },
    {
     "alias": "Email",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Email' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Email" }
     ]
    },
    {
     "alias": "Media",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Media' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Media" }
     ]
    },
    {
     "alias": "Network",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Network' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Network" }
     ]
    },
    {
     "alias": "RemoteAccess",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'RemoteAccess' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "RemoteAccess" }
     ]
    },
    {
     "alias": "SocialNetwork",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'SocialNetwork' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "SocialNetwork" }
     ]
    },
    {
     "alias": "Straming",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Streaming' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Streaming" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'System' AND \"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "Unspecified",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Unspecified' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Unspecified" }
     ]
    },
    {
     "alias": "VPN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'VPN' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "VPN" }
     ]
    },
    {
     "alias": "Video",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Video' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Video" }
     ]
    },
    {
     "alias": "VoIP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'VoIP' AND \"host\" = '${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "VoIP" }
     ]
    },
    {
     "alias": "Web",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:ndpi_categories",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 5m) + non_negative_derivative(mean(\"bytes_sent\"), 5m) FROM \"host:ndpi_categories\" WHERE (\"category\" = 'Web' AND \"host\" = '/^$host$/') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Web" }
     ]
    }
   ]
  },
  {
   "title": "Active Flows",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 24 },
   "targets": [
    {
     "alias": "as Client",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:active_flows",
     "query": "SELECT mean(\"flows_as_client\") FROM \"host:active_flows\" WHERE (\"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "flows_as_client" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "as Server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "host:active_flows",
     "query": "SELECT mean(\"flows_as_server\") FROM \"host:active_flows\" WHERE (\"host\" ='${host}') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "flows_as_server" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}