{
 "title": "Network Status - ntopng",
 "description": "Analyze the network status using ntopng as source of data and display them using Grafana",
 "tags": [
  "ntopng",
  "alerts",
  "flows",
  "score"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Interface Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Score",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:score",
     "query": "SELECT mean(\"cli_score\") + mean(\"srv_score\") FROM \"iface:score\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cli_score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "srv_score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "description": "Interface traffic chart, both RX and TX",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Traffic RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iface:traffic_rxtx",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) FROM \"iface:traffic_rxtx\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Traffix TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iface:traffic_rxtx",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interface Activity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Interface Inactivity",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:traffic",
     "query": "SELECT count(*) as num_inactive FROM (SELECT non_negative_derivative(mean(\"bytes\"), 10s) as Traffic FROM \"iface:traffic\" WHERE $timeFilter GROUP BY time(1s) fill(null)) where Traffic = 0",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Interface Activity",
     "query": "SELECT count(*) as num_active FROM (SELECT non_negative_derivative(mean(\"bytes\"), 10s) as Traffic FROM \"iface:traffic\" WHERE $timeFilter GROUP BY time(1s) fill(null)) where Traffic != 0"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT Host, Hostname, sum(Traffic) as Traffic FROM (\nSELECT IPv4NumToString(IPV4_DST_ADDR) as Host, DST_LABEL as Hostname, sum(TOTAL_BYTES) as Traffic FROM ntopng.flows WHERE (IPV4_DST_ADDR != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv4NumToString(IPV4_SRC_ADDR) as Host, SRC_LABEL as Hostname, sum(TOTAL_BYTES) as Traffic FROM ntopng.flows WHERE (IPV4_SRC_ADDR != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv6NumToString(IPV6_SRC_ADDR) as Host, SRC_LABEL as Hostname, sum(TOTAL_BYTES) as Traffic FROM ntopng.flows WHERE (IPV6_SRC_ADDR != IPv6StringToNum('::')) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv6NumToString(IPV6_DST_ADDR) as Host, DST_LABEL as Hostname, sum(TOTAL_BYTES) as Traffic FROM ntopng.flows WHERE (IPV6_DST_ADDR != IPv6StringToNum('::')) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname\n) GROUP BY Host, Hostname ORDER BY Traffic DESC LIMIT 30"
    }
   ]
  },
  {
   "title": "Active Hosts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active Hosts",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iface:hosts",
     "select": [
      [
       { "params": [ "num_hosts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Countries Seen",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Country, count(*) as Flows FROM (\nSELECT char(bitShiftRight(SRC_COUNTRY_CODE, 8), bitAnd(SRC_COUNTRY_CODE, 0xFF)) as Country FROM ntopng.flows WHERE (SRC_COUNTRY_CODE != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) UNION ALL \nSELECT char(bitShiftRight(DST_COUNTRY_CODE, 8), bitAnd(DST_COUNTRY_CODE, 0xFF)) as Country FROM ntopng.flows WHERE (DST_COUNTRY_CODE != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) \n) WHERE Country != '' GROUP BY Country"
    }
   ]
  },
  {
   "title": "Top Alerted Hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Host, Hostname, Score, sum(Alerts) as Alerts FROM (\nSELECT IPv4NumToString(IPV4_DST_ADDR) as Host, DST_LABEL as Hostname, sum(SCORE) as Score, count(*) as Alerts FROM ntopng.flows WHERE (IPV4_DST_ADDR != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv4NumToString(IPV4_SRC_ADDR) as Host, SRC_LABEL as Hostname, sum(SCORE) as Score, count(*) as Alerts FROM ntopng.flows WHERE (IPV4_SRC_ADDR != 0) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv6NumToString(IPV6_SRC_ADDR) as Host, SRC_LABEL as Hostname, sum(SCORE) as Score, count(*) as Alerts FROM ntopng.flows WHERE (IPV6_SRC_ADDR != IPv6StringToNum('::')) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname UNION ALL \nSELECT IPv6NumToString(IPV6_DST_ADDR) as Host, DST_LABEL as Hostname, sum(SCORE) as Score, count(*) as Alerts FROM ntopng.flows WHERE (IPV6_DST_ADDR != IPv6StringToNum('::')) AND (FIRST_SEEN >= ${__from:date:seconds}) AND (LAST_SEEN <= ${__to:date:seconds}) GROUP BY Host, Hostname\n) GROUP BY Host, Hostname, Score ORDER BY Score DESC LIMIT 30"
    }
   ]
  }
 ]
}