#!/bin/sh

LUA_INTERPR="lua5.3"

if which ${LUA_INTERPR} 2>&1 >/dev/null; then
  if hash ${LUA_INTERPR} 2>/dev/null; then
    # Sort locales
    for fname in `ls scripts/locales`; do
	full_path=scripts/locales/${fname}

	if ! git diff --staged --quiet $full_path; then
	    locale=${fname%%.lua}
	    tools/localization/localize.sh sort $locale
	    git add $full_path
	fi
    done
  else
    echo "$0: ${LUA_INTERPR} could not be found"
  fi
fi
