/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DisplayFormatter } from "./types/DisplayFormatter";
export namespace Components {
    interface NtopDatasource {
        "name"?: string;
        "src": any;
        "styles"?: string;
        "type"?: string;
    }
    interface NtopWidget {
        "displayFormatter": DisplayFormatter;
        "height": string;
        "type": string;
        /**
          * The refresh time for the widge,
         */
        "update": number;
        "width": string;
    }
}
declare global {
    interface HTMLNtopDatasourceElement extends Components.NtopDatasource, HTMLStencilElement {
    }
    var HTMLNtopDatasourceElement: {
        prototype: HTMLNtopDatasourceElement;
        new (): HTMLNtopDatasourceElement;
    };
    interface HTMLNtopWidgetElement extends Components.NtopWidget, HTMLStencilElement {
    }
    var HTMLNtopWidgetElement: {
        prototype: HTMLNtopWidgetElement;
        new (): HTMLNtopWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "ntop-datasource": HTMLNtopDatasourceElement;
        "ntop-widget": HTMLNtopWidgetElement;
    }
}
declare namespace LocalJSX {
    interface NtopDatasource {
        "name"?: string;
        "onSrcChanged"?: (event: CustomEvent<string>) => void;
        "src": any;
        "styles"?: string;
        "type"?: string;
    }
    interface NtopWidget {
        "displayFormatter"?: DisplayFormatter;
        "height": string;
        "type"?: string;
        /**
          * The refresh time for the widge,
         */
        "update"?: number;
        "width": string;
    }
    interface IntrinsicElements {
        "ntop-datasource": NtopDatasource;
        "ntop-widget": NtopWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ntop-datasource": LocalJSX.NtopDatasource & JSXBase.HTMLAttributes<HTMLNtopDatasourceElement>;
            "ntop-widget": LocalJSX.NtopWidget & JSXBase.HTMLAttributes<HTMLNtopWidgetElement>;
        }
    }
}
