--
-- (C) 2014-20 - ntop.org
--

local dirs = ntop.getDirs()
package.path = dirs.installdir .. "/scripts/lua/modules/?.lua;" .. package.path

require "lua_utils"

local json = require("dkjson")

local system_utils = {}

-- #################################

function system_utils.systemHostStats()
   local system_host_stats =  ntop.systemHostStat()

   -- TODO: add CPU states stats generated by cpu_states_monitor.lua

   return system_host_stats
end

-- #################################

return system_utils

